from __future__ import annotations

from typing import Protocol

from app.models.schemas import ChunkRecord, ClaimRecord, DocumentRecord, EntityRecord, GraphEdge


class GraphStore(Protocol):
    def ensure_schema(self) -> None: ...

    def upsert_document(self, document: DocumentRecord) -> None: ...

    def upsert_chunks(self, chunks: list[ChunkRecord]) -> None: ...

    def upsert_entities(self, entities: list[EntityRecord]) -> None: ...

    def upsert_claims(self, claims: list[ClaimRecord]) -> None: ...

    def upsert_edges(self, edges: list[GraphEdge]) -> None: ...

    def get_chunks(self, chunk_ids: list[str]) -> list[ChunkRecord]: ...

    def search_entities(self, query: str, limit: int = 5) -> list[EntityRecord]: ...

    def claims_for_entities(self, entity_ids: list[str], limit: int = 10) -> list[ClaimRecord]: ...

    def close(self) -> None: ...
